### ISSUE TITLE
Show Date/Time in Buddhist Era

### ISSUE THREAD

**Issue by piruin** [OCA/l10n-thailand#370]
Is there have solution to show data/time year in Buddhist Era on Odoo UI when user language is Thai?

**Comment by Saran440** [comment]
What is reason for  show date thai?
For me, users require Thai dates on forms and reports. Therefore, we customize it instead of relying on the default UX/UI in Odoo. This approach is safe and easy.

However, I think It posible to show date year thai if you can write JS (owl) for add new widget <date_thai>.
but we not experts in JS.
